### ISSUE TITLE
Tagbar config included upstream

### ISSUE THREAD

**Issue by janlarres** [bitterjug/vim-tagbar-ctags-elm#3]
Hi! I am currently updating the Universal-Ctags definitions in Tagbar and discovered that you added an Elm parser to the project, and also a Tagbar configuration for it here. Since the parser is part of the main uctags project now I have added your Tagbar configuration to Tagbar itself: https://github.com/majutsushi/tagbar/commit/b4643521ff5a4937ac383f658dcda15c0fb2400d I hope you're okay with that. If you would like to maintain that configuration in the future so that it stays in sync with changes in the parser, please let me know.

**Comment by bitterjug** [comment]
Hi Sorry for being slow to reply to this. Yes, I'm delighted that you've included my tagbar config, as I said in the readme, that was always the plan. I'm aware of a couple of things the ctags config doesn't handle well and they're adding cool features fast so I might want to go back and revisit it when scoped tags are up and working. In which case, I'll give you a PR. Thanks for finding this!
